name: GitHub Actions Demo
on: [push]
jobs:
  Create_PostgresSql_Server:
    runs-on: ubuntu-latest
    container: postgres:alpine
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: postgres -V
      - run: psql -U postgres
      - run: CREATE DATABASE bugtrace;


        
