name: GitHub Actions Demo
on: [push]
jobs:
  Create_PostgresSql_Server:
    runs-on: ubuntu-latest
    container: postgres:alpine
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
      
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
          POSTGRES_DB: bugtrace
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
       

    steps:          
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Query database
        run: psql -h postgres -d bugtrace -U postgres -c 'SELECT 1;'
        env:
          PGPASSWORD: postgres
      - run: postgres -V


        
